application: your-application-id-here
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

# This handler tells app engine how to route requests to a WSGI application.
# The script value is in the format <path.to.module>.<wsgi_application>
# where <wsgi_application> is a WSGI application object.
- url: .*  # This regex directs all routes to main.app
  script: main.app
